### PR TITLE
1.19.2: Fix compatibility with Fabric API 0.77.0

### PR DESCRIPTION
**Pull request by unilock**
Same as #40, but just cherry-picks commits from newer branches instead of reinventing the wheel.

Also removes the Iris mixins, as it seems they no longer do anything.

### CODE REVIEW

**Review by Pyrofab — APPROVED** [review]
Thanks for the backport 👍

**Comment by Abalieno** [comment]
Not sure how/if related.

The new loader crashes other mods like Create, on startup, with this error message:
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5944.method_34583(String, Object)" because "$$2" is null

Due to this:
https://github.com/FabricMC/fabric/issues/3466

As mentioned there, I figured out that in another case the same crash didn't happen because I had the mod miskatonicmysteries, that includes satin, and doesn't actually crash.

This is the old 1.9.0 version of the mod, though. Which worked to solve the issue. Though I'm not sure if it then maybe crashes later while playing...

Now the problem is that I added the recent 1.9.1 and I got the crash instead. But in this case it launched normally, and it crashed for some reason while I was idling in the menu screen.

So I'm wondering why old Satin fixed that crash, whereas for some reason the new one has a different problem. Or maybe this other problem is unrelated to the new version and existed in the old one too, I just didn't trigger it...

**Comment by Pyrofab** [comment]
That is very weird, the previous version of satin should straight up crash with newer Fabric API...

**Comment by Abalieno** [comment]
It SOLVES the crash. Maybe it overrides the fabric method that is now incompatible with mods like Create?

And then maybe you updated it to remove the method, so that Fabric new one is used, and so restoring the incompatibility... is my guess.

**Comment by unilock** [comment]
@Abalieno I think the issue you're running into is due to an outdated version of Porting Lib embedded in some other mod, which can be fixed by adding [v2.1.1167+1.19.2](https://modrinth.com/mod/porting_lib/version/2.1.1167+1.19.2) of Porting Lib as an independent mod (which will then override the older version(s) present).

Though I'm not sure how Satin API relates to the issue?

**Comment by Abalieno** [comment]
Because it's shader code that breaks in porting lib, same as here. I just suspect satin overrides the same piece of code. I only know it stops the crash.

It has always been advised NOT to use porting lib separately, so I'm not sure that won't lead to more issues.

**Comment by Pyrofab** [comment]
Shouldn't cause issues if you stay on the latest version, usually authors tell you not to install separately because the bundled version is supposed to be enough and there is normally no benefit to installing those libraries by themselves

**Comment by unilock** [comment]
> It has always been advised NOT to use porting lib separately...

I've never heard of that. Regardless, I've played through multiple large modpacks with Porting Lib in the mods folder as a separate JAR without issue.

**Pull request merged**
